// generated by mBlock5 for <your product>
// codes make you happy

#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  pinMode(6,OUTPUT);
  pinMode(7,OUTPUT);
  pinMode(5,OUTPUT);
  pinMode(4,OUTPUT);
  // MTR A forward 100% speed
  analogWrite(6,map(100, 0, 100, 0, 1000)); //set PWM
  _delay(2);
  // Stop MTR A
  analogWrite(6,map(0, 0, 100, 0, 1000));
  digitalWrite(7,0);
  _delay(2);
  // MTR A backward
  digitalWrite(7,1);
  _delay(2);
  // Stop MTR A
  analogWrite(6,map(0, 0, 100, 0, 1000));
  digitalWrite(7,0);
  _delay(2);
  // MTR B forward 100% speed
  analogWrite(5,map(100, 0, 100, 0, 1000));
  _delay(2);
  // Stop MTR B
  analogWrite(5,map(0, 0, 100, 0, 1000));
  digitalWrite(4,0);
  _delay(2);
  // MTR B backward
  digitalWrite(4,1);
  _delay(2);
  // Stop MTR B
  analogWrite(5,map(0, 0, 100, 0, 1000));
  digitalWrite(4,0);

}

void _loop() {
}

void loop() {
  _loop();
}